name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.7
            TOXENV: "py37"
          - python-version: 3.8
            TOXENV: "py38"
          - python-version: 3.9
            TOXENV: "py39"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: pip install --upgrade pip tox --user
      - name: Test with tox 
        env:
          TOXENV: ${{ matrix.TOXENV }}
        run: python -m tox

  test_macOS:
    runs-on: macOS-latest
    strategy:
      matrix:
        include:
          - python-version: 3.7
            TOXENV: "py37"
          - python-version: 3.8
            TOXENV: "py38"
          - python-version: 3.9
            TOXENV: "py39"
          - python-version: "3.10"
            TOXENV: "py310"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: pip install --upgrade pip tox --user
      - name: Test with tox
        env:
          TOXENV: ${{ matrix.TOXENV }}
        run: python -m tox

  test_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - python-version: 3.7
            TOXENV: "py37"
          - python-version: 3.8
            TOXENV: "py38"
          - python-version: 3.9
            TOXENV: "py39"
          - python-version: "3.10"
            TOXENV: "py310"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: pip install --upgrade pip tox --user
      - name: Test with tox
        env:
          TOXENV: ${{ matrix.TOXENV }}
        run: python -m tox
